### ISSUE TITLE
ERROR:  CANNOT WITHDRAW ETH

### ISSUE THREAD

**Issue by piyushcoader** [wavesplatform/WavesGUI#392] opened 2017-12-20 09:12 UTC
Hi. So I have a problem with withdrawing ETH from Waves wallet. I tried to do this from Chrome extension, Chrome browser and Safari browser. Seems like this problem is global since I see this error in developer tools console - Base58.decode received unacceptable input. Character '0' is not in the Base58 alphabet

**Comment by xenohunter** [comment] 2017-12-20 14:09
Hello! Thanks for reaching out. We will investigate it soon.

**Comment by xenohunter** [comment] 2017-12-22 13:10
Hello again! Sorry, I couldn't reproduce the bug.

**Comment by piyushcoader** [comment] 2017-12-22 19:05
are you able to send ETH to other wallet from https://waveswallet.io/?

**Comment by piyushcoader** [comment] 2017-12-22 19:06
here is the stacktrace
```
Base58.decode received unacceptable input. Character '0' is not in the Base58 alphabet.
waves-lite-client-mainnet-0.5.11.js:25491:16
consoleLog/<
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:25491:16
$ExceptionHandlerProvider/this.$get</<
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:21907:7
$apply
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:29322:11
ngEventHandler/<
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:38153:17
dispatch
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:5200:16
add/elemData.handle
https://waveswallet.io/js/waves-lite-client-mainnet-0.5.11.js:5009:6
```

**Comment by xenohunter** [comment] 2017-12-25 13:20
That is very strange. I could send it on Friday, and haven't checked it yet this week. Nothing alike that stack trace has emerged ever. Might there be some connectivity issue with Coinomat? Does the problem persist?

**Comment by piyushcoader** [comment] 2018-01-02 15:01
yes i am still getting same error also no luck with beta waves platform

**Comment by xenohunter** [comment] 2018-05-10 15:35
Hello again. If the error persists then, please, reopen the issue. Right now I'm closing it.

**Closed by xenohunter** 2018-05-10 15:35 UTC
Labels: bug
