### ISSUE TITLE
WalletGui does not download the folder "Locale"

### ISSUE THREAD

**Issue by Cristyander** [wavesplatform/WavesGUI#1374] opened 2019-06-13 04:38 UTC
remote: [BABEL] Note: The code generator has deoptimised the styling of "/tmp/build_a739aea8b47da76212a527da7960fcae/dist/tmp/js/bundle.js" as it exceeds the max of "500KB".
remote: Locales did not loaded: Error: Client network socket disconnected before secure TLS connection was established
remote:        [04:33:47] Finished 'downloadLocales' after 10 s
remote:        [04:33:47] Starting 'copy-web-testnet-normal'...
remote:        [04:33:47] Starting 'copy-web-testnet-min'...
remote:        [04:33:47] Starting 'copy-web-mainnet-normal'...
remote:        [04:33:47] Starting 'copy-web-mainnet-min'...
remote:        [04:33:47] Starting 'copy-desktop-testnet-normal'...
remote:        [04:33:47] Starting 'copy-desktop-testnet-min'...
remote:        [04:33:47] Starting 'copy-desktop-mainnet-normal'...
remote:        [04:33:47] Starting 'copy-desktop-mainnet-min'...
remote:        [04:33:47] 'copy-web-testnet-normal' errored after 15 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-web-testnet-min' errored after 15 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-web-mainnet-normal' errored after 16 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-web-mainnet-min' errored after 16 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-desktop-testnet-normal' errored after 16 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-desktop-testnet-min' errored after 16 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-desktop-mainnet-normal' errored after 15 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'
remote:        [04:33:47] 'copy-desktop-mainnet-min' errored after 15 ms
remote:        [04:33:47] Error: ENOENT: no such file or directory, lstat 'dist/locale'

to run I had to paste a locale folder from an old version at compile time.

**Comment by tsigel** [comment] 2019-06-13 09:19
This issue is duplicate of [issues/1373](https://github.com/wavesplatform/WavesGUI/issues/1373).
U has problem with download locales zip file.

**Closed by tsigel** 2019-06-13 09:19 UTC
