### ISSUE TITLE
Burn spam token

### ISSUE THREAD

**Issue by travek** [wavesplatform/WavesGUI#655] opened 2018-05-22 11:38 UTC
Hi!

While official Waves airdrop is ongoing many users face the same issue - some spam tokens arrived to users wallets. Example are assets with names WGO.store, mcfly.tk, WBTC.TK, WBTC.me. I even don't want to know is it scam or not, doesn't matter. I (and I hope not only) want to see in their wallets only official "legal" tokens.

We need to have some filters in the wallet on this spam tokens massive payments. Let's request and have this feature.
We need to have a simple way how to safely "delete" these spam tokens from the wallets.

Could you please comment on these topics and propose solutions

**Comment by travek** [comment] 2018-05-22 11:54
My be it is a reasonable to have in the wallet a feature (checkbox in settings) "allow Mass payment" and to have a filter for what tokens (assets) Mass payments for the wallet are avaliable.
If I don't want to receive Mass payments except in BCC, WCT, LIQUID then I will do this parameterization and will block all spam assets distributions.

**Comment by jasny** [comment] 2018-05-22 15:33
Duplicate of #654 

You can already burn tokens. However, this costs 0.001 Waves per asset. Hiding them from your wallet is free.

Currently, Waves doesn't allow for a wallet to deny a token. Specifying this just in the wallet doesn't help. Having a SPAM folder seems like the easiest way to battle this issue.

**Comment by travek** [comment] 2018-05-22 15:42
@jasny 
1) Could you give instructions how to burn tokens from my wallet.

2) Re SPAM folder. I find you proposal reasonable. We need to have a filter in the wallet that will turn on automatical moving of spam tokens into this folder
3) Redirection from the wallet on the (http) addressed of spam tokens should be forbiddent. If spam token name is an http link then redirection on any http address should be forbidden in any case.

**Comment by travek** [comment] 2018-05-22 19:25
@jasny 
Done

I think we could think more about spam defence. Definetely it willbe a problem while adoption increase. Currenly it's totally not user friendly, like many of us don't whant to have handreds "viagra"mails in our mail box. Let'sthink of that problem more deeply.

Indeed burning tokens with Waves costs is not a good idea - I can burn them today andidiot spammers will fillmy wallet with spam tokens tom.

**Comment by tsigel** [comment] 2018-11-01 08:48
Hi! 
We have a [list](https://raw.githubusercontent.com/wavesplatform/waves-community/master/Scam%20tokens%20according%20to%20the%20opinion%20of%20Waves%20Community.csv) of spam tokens that complements the Waves community.

**Closed** 2018-11-06 08:53 UTC
